config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'search#new'
    
    get '/search_offline', to: 'search#search_offline'
    
    get '/company_info', to: 'search#company_info'
    
    get '/company_info_offline', to: 'search#company_info_offline'
    
    get '/help', to: 'static_pages#help'
    
    get '/about', to: 'static_pages#about'
    
    get '/contact', to: 'static_pages#contact'

end

app/models/search.rb
class Search 
    require 'will_paginate/array'
    
    attr_reader :searchResult, :company, :country

    def initialize(searchString = {})
        @company = searchString[:company]
        @country = searchString[:country]
    end

    def execute_search
        ######### Save search results to a .json file
        #atokaResult = search_atoka
        #File.open("temp.json","w") do |f|
        #    f.write(atokaResult.to_json)
        #end
        
        ######### online search
        ocResult = search_open_corporates
        atokaResult = search_atoka
        @searchResult = merge_search_results(ocResult, atokaResult)
    end

    def search_atoka
        atokaToken = ENV['ATOKA_TOKEN']

        if company_defined? && !country_defined?
            url = "https://api.atoka.io/v2/companies?token=" + atokaToken.to_s + "&packages=*" + "&name=" + @company.to_s + "&limit=50" + "&offset=0"
            response = HTTParty.get(url)
            atokaSearchResult = response.parsed_response["items"]
            totalItems = response.parsed_response["meta"]["count"].to_i

            #If number of items in the result is larger than the response limit, then request the next 50 until total items have been retrieved 
            if totalItems > 50
                currentRequest = 0
                offset = 50
                additionalRequests = totalItems / 50

                while currentRequest < additionalRequests do
                    nextPageURL = "https://api.atoka.io/v2/companies?token=" + atokaToken.to_s + "&packages=*" + "&name=" + @company.to_s + "&limit=50" + "&offset=" + offset.to_s
                    nextPageResponse = HTTParty.get(nextPageURL)
                    nextPageCompanies = nextPageResponse.parsed_response["items"]
                    atokaSearchResult.concat(nextPageCompanies)

                    offset += 50
                    currentRequest += 1
                end
                atokaSearchResult
            else  
                atokaSearchResult
            end  

        elsif company_defined? && country_defined?
            @country = "uk" if @country == "gb" #Atoka currently accepts 'it', 'uk', 'ru', or '*' as country value

            if @country != "it" || @country != "uk" || @country != "ru"
                @country = "*"
            end

            url = "https://api.atoka.io/v2/companies?token=" + atokaToken.to_s + "&packages=*" + "&name=" + @company.to_s + "&countries=" + @country.to_s + "&limit=50" + "&offset=0" 
            response = HTTParty.get(url)
            atokaSearchResult = response.parsed_response["items"]
            totalItems = response.parsed_response["meta"]["count"].to_i

            if totalItems > 50
                currentRequest = 0
                offset = 50
                additionalRequests = totalItems / 50

                while currentRequest < additionalRequests do
                    nextPageURL = "https://api.atoka.io/v2/companies?token=" + atokaToken.to_s + "&packages=*" + "&name=" + @company.to_s + "&countries=" + @country.to_s + "&limit=50" + "&offset=" + offset.to_s
                    nextPageResponse = HTTParty.get(nextPageURL)
                    nextPageCompanies = nextPageResponse.parsed_response["items"]
                    atokaSearchResult.concat(nextPageCompanies)

                    offset += 50
                    currentRequest += 1
                end
                atokaSearchResult
            else
                atokaSearchResult
            end

        else
            atokaSearchResult = []
        end

    end

    def search_open_corporates
        ocToken = ENV['OC_TOKEN']

        if company_defined? && !country_defined?
            url = "https://api.opencorporates.com/v0.4/companies/search?api_token=" + ocToken.to_s + "&q=" + @company.to_s
            response = HTTParty.get(url)
            ocSearchResult = response.parsed_response["results"]["companies"]
            totalPages = response.parsed_response["results"]["total_pages"].to_i

            #if totalPages > 20
            #    totalPages = 20
            #end

            if totalPages > 1
                (2..totalPages).each do |page|
                    nextPageURL = "https://api.opencorporates.com/v0.4/companies/search?api_token=" + ocToken.to_s + "&q=" + @company.to_s + "&page=#{page}"
                    nextPageResponse = HTTParty.get(nextPageURL)
                    nextPageCompanies = nextPageResponse.parsed_response["results"]["companies"]
                    ocSearchResult.concat(nextPageCompanies)
                end
                ocSearchResult
            else
                ocSearchResult
            end
        elsif company_defined? && country_defined?
            url = "https://api.opencorporates.com/v0.4/companies/search?api_token=" + ocToken.to_s + "&q=" + @company.to_s + "&jurisdiction_code=" + @country.to_s
            response = HTTParty.get(url)
            totalPages = response.parsed_response["results"]["total_pages"].to_i
            ocSearchResult = response.parsed_response["results"]["companies"]

            #if totalPages > 20
            #    totalPages = 20
            #end

            if totalPages > 1
                (2..totalPages).each do |page| 
                    nextPageURL = "https://api.opencorporates.com/v0.4/companies/search?api_token=" + ocToken.to_s + "&q=" + @company.to_s + "&jurisdiction_code=" + @country.to_s + "&page=#{page}" 
                    nextPageResponse = HTTParty.get(nextPageURL) 
                    nextPageCompanies = nextPageResponse.parsed_response["results"]["companies"] 
                    ocSearchResult.concat(nextPageCompanies) 
                end 
                ocSearchResult 
            else 
                ocSearchResult 
            end 
        else 
            ocSearchResult = [] 
        end 
    end

    def merge_search_results(ocResult, atokaResult)
        mergedResult = [] 

        ocResult.each do |ocCompany|

            atokaResult.each do |atokaCompany|

                if ocCompany["company"]["company_number"].to_s == atokaCompany["base"]["rea"].to_s
                    ocCompany["company"]["atoka_company_id"] = atokaCompany["id"].to_s
                end

            end
            mergedResult << ocCompany
        end

        mergedResult
    end

    def search_company_oc(country, companyID)
        ocToken = ENV['OC_TOKEN']
        url = "https://api.opencorporates.com/v0.4/companies/" + country.to_s + "/" + companyID.to_s + "?api_token=" + ocToken.to_s
        response = HTTParty.get(url)
        response.parsed_response["results"]["company"]
    end

    def search_company_atoka(companyID)
        atokaToken = ENV['ATOKA_TOKEN']
        url = "https://api.atoka.io/v2/companies/" + companyID.to_s + "?token=" + atokaToken.to_s + "&packages=*"
        response = HTTParty.get(url)
        response.parsed_response["item"]
    end

    def company_defined?
        !@company.to_s.empty?
    end

    def country_defined?
        !@country.to_s.empty?
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def new
        newSearch = Search.new({company: params[:search], country: params[:jurisdictionFilter]})   
        newSearch.execute_search
        @resultSet = newSearch.searchResult.paginate(:page => params[:page], :per_page => 30)
        @MVPMode = "online"
    end

    def search_offline
        newSearch = SearchOffline.new({company: params[:search], country: params[:jurisdictionFilter]})   
        newSearch.execute_search
        @searchResultSetLocal = newSearch.searchResultLocal.paginate(:page => params[:page], :per_page => 30)
        @MVPMode = "offline"
    end

    def company_info
        if params[:MVPMode] == "online" 
            newSearch = Search.new()
            ocCompany = newSearch.search_company_oc(params[:ocJurisdictionCode], params[:ocCompanyNumber]) 
            atokaCompany = newSearch.search_company_atoka(params[:atokaCompanyNumber]) 
            @companyInfo = [ocCompany, atokaCompany]
        end
    end

    def company_info_offline
        if params[:MVPMode] == "offline" 
            newSearch = SearchOffline.new()
            ocCompany = newSearch.search_company_oc_offline(params[:ocCompanyNumber]) 
            @ocCompanyInfoOffline = ocCompany
            
            #atokaCompany = newSearch.search_company_atoka_offline(params[:atokaCompanyNumber]) 
            #@companyInfo = [ocCompany, atokaCompany]
        end
    end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_altcmp_btn_end.html.erb
</ul>
</div> 
</td>

app/views/search/_altcmp_btn_start.html.erb
<td class="warning">
    <div class="dropdown">
        <button class="btn-small btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Alternative Info
            <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right">
            

app/views/search/company_info_offline.html.erb
<% provide(:title, "Compnay info")  %>
<div class="container">

<% resp = @ocCompanyInfoOffline %>
<% foundingDate = resp[0]["foundingDate"]["value"] %>
<% dissolutionDate = resp[0]["dissolutionDate"]["value"] %>
<% fd = DateTime.parse(foundingDate) %>
<% dd = DateTime.parse(dissolutionDate) %>
    
<h3> <%= resp[0]["legalName"]["value"] %> </h3>

<table class="table table-responsive table-bordered table-condensed">
        <tbody>
            <tr>
                <th class="active">Company</th>
                <th class="active">Data from OpenCorporates (RDF database)</th>
            </tr>
            <tr>
                <td>Legal Name</td>
                <td> <%= resp[0]["legalName"]["value"] %> </td>
            </tr>
            <tr>
                <td>Trading As</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Startup</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Publicly Traded</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <th colspan="2" class="active">Company Dates and Status</th>
            </tr>
            <tr>
                <td>Incorporation Date</td>
                <td> <%= fd.utc() %> </td>
            </tr>
            <tr>
                <td>Dissolution Date</td>
                <td> <%= dd.utc() %> </td>
            </tr>
            <tr>
                <td>Current Status</td>
                <td> <%= resp[0]["orgStatusText"]["value"] %> </td>
            </tr>
            <tr>
                <th colspan="2" class="active">Company Type</th>
            </tr>
            <tr>
                <td>Company Type Name</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Public Sector Organization</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Public Sector: type of entity</td>
                <td> &nbsp; </td>
            <tr>
                <th colspan="2" class="active">Economic Classification</th>
            </tr>
            <tr>
                <td>UKSIC</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <th colspan="2" class="active">Physical Presence</th>
            </tr>
            <tr>
                <td>Registered Address</td>
                <td> <%= resp[0]["fullAddress"]["value"] %> </td>
            </tr>
            <tr>
                <td>Jurisdiction / Country Code</td>
                <td> <%= resp[0]["jurisdiction"]["value"] %> </td>
            </tr>
            <tr>
                <th colspan="2" class="active">Electronic Presence</th>
            </tr>
            <tr>
                <td>Wikipedia URI</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <th colspan="2" class="active">Identifiers</th>
            </tr>
            <tr>
                <td>Company Number</td>
                <td> <%= resp[0]["identifier"]["value"] %> </td>
            </tr>
            <tr>
                <td>Companies House Company Number</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Atoka ID</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>Open Corporates URI</td>
                <td> &nbsp; </td>
            </tr>
            <tr>
                <td>IT IPA Code</td>
                <td> &nbsp; </td>
            </tr>
        </tbody>
    </table> 
    
    
</div>

app/views/search/new.html.erb
<% provide(:title, "Federated Search")  %>
<div class="container jumbotron">

    <div class="row">
        <div class="col-xs-8 col-xs-offset-3">
            <%= form_tag root_path, :method => 'get', :class => 'form-inline' do %>
            <div class="form-group">
                <%= label_tag 'company' %>
                <%= text_field_tag :search, params[:search], :placeholder => 'Company name', :class => 'form-control' %>
            </div>
            <div class="form-group">
                <%= label_tag 'country' %>
                <%= select_tag :jurisdictionFilter, options_for_select([["All", ""], ["Norway", "no"], ["Italy", "it"], ["Great Britain", "gb"]]), :class => 'form-control' %>
            </div>
            <%= button_tag "Search (Federated)", :name => nil, :class => "btn btn-default" %>
        </div>
        <% end %>
    </div>

    <div>
        <% if @resultSet && @resultSet.any? %>
        <%= will_paginate @resultSet %>
        <p>
            <% @resultSet.each do |company| %>
            <%= link_to company["company"]["name"], company_info_path( :ocJurisdictionCode => "#{company["company"]["jurisdiction_code"]}", :ocCompanyNumber => "#{company["company"]["company_number"]}", :atokaCompanyNumber => "#{company["company"]["atoka_company_id"]}", :MVPMode => "#{@MVPMode}" ), :html => { :class => "btn" } %> 

            <% if company["company"]["atoka_company_id"] %>
            <%= image_tag("AtokaLogoSmall.png", size: "22x22") %>
            <% end %>

            <% if company["company"]["source"] && company["company"]["source"]["publisher"] == "Brønnøysundregistrene" %>
            <%= image_tag("BrregLogoSmall.png", size: "22x22") %>
            <% end %>

            <%= image_tag("OCLogoSmall.png", size: "22x22") %>
            <br/>
            <% end %>
        </p>
        <%= will_paginate @resultSet %>
        <% end %>
    </div>

</div>

app/views/search/result.html.erb
<% provide(:title, "Result")  %>
<div class="container jumbotron">


    
</div>

app/views/search/search_offline.html.erb
<% provide(:title, "Local S4 Search")  %>
<div class="container jumbotron">

    <div class="row">
        <div class="col-xs-8 col-xs-offset-3">
            <%= form_tag search_offline_path, :method => 'get', :class => 'form-inline' do %>
            <div class="form-group">
                <%= label_tag 'company' %>
                <%= text_field_tag :search, params[:search], :placeholder => 'Company name', :class => 'form-control' %>
            </div>
            <div class="form-group disabled">
                <%= label_tag 'country' %>
                <%= select_tag :jurisdictionFilter, options_for_select([["All", ""], ["Norway", "no"], ["Italy", "it"], ["Great Britain", "gb"]]), :class => 'form-control' %>
            </div>
            <%= button_tag "Search (Local)", :name => nil, :class => "btn btn-default" %>
        </div>
        <% end %>
    </div>

    <div>
        <% if @searchResultSetLocal && @searchResultSetLocal.any? %>
        <%= will_paginate @searchResultSetLocal %>
        <p>
            <% @searchResultSetLocal.each do |company| %>
            <%= link_to company["legalName"]["value"], company_info_offline_path( :ocJurisdictionCode => "#{company["jurisdiction"]["value"]}", :ocCompanyNumber => "#{company["identifier"]["value"]}", :atokaCompanyNumber => "", :MVPMode => "#{@MVPMode}" ), 
            :html => { :class => "btn" } %>

            <br/>
            <% end %>
        </p>
        <%= will_paginate @searchResultSetLocal %>
        <% end %>
        
    </div>

</div> 