config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'search#new'
    
    get '/search_offline', to: 'search#search_offline'
    
    get '/company_info', to: 'search#company_info'
    
    get '/company_info_offline', to: 'search#company_info_offline'
    
    get '/help', to: 'static_pages#help'
    
    get '/about', to: 'static_pages#about'
    
    get '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
    <div class="container">
    <small>
        The Minimum Viable Product (MVP) - EU Business Graph
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "MVP", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Search", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <li>
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select MVP Mode
                            <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Federated search", root_path %></li>
                            <li><%= link_to "Local search", search_offline_path %></li>
                        </ul>
                    </div> 
                </li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%= render 'layouts/shim' %>
    </head>

    <body>
        <%= render 'layouts/header' %>

        <div class="container">
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>
    </body>
</html>